Problems for model download #5  
https://github.com/evolutionaryscale/esm/issues/5  

from_pretrained() Error. Cannot use a path to import local model?  #132  
https://github.com/evolutionaryscale/esm/issues/132

## working with ESM2 embeddings

In [1]:
from scprint.tokenizers import protein_embeddings_generator
#from RNABERT import RNABERT

from scdataloader.utils import load_genes
import pandas as pd

%load_ext autoreload
%autoreload 2

→ connected lamindb: zhang0730/lamin_data

# human

In [2]:
import bionty as bt
bt.core.sync_all_sources_to_latest()

! please reload your instance to reflect the updates!

In [3]:
from scdataloader.utils import populate_my_ontology
populate_my_ontology()

→ returning existing CellType record with same name: 'unknown'
→ returning existing Organism record with same name: 'unknown'
→ returning existing Phenotype record with same name: 'unknown'
→ returning existing Ethnicity record with same name: 'unknown'
→ returning existing ExperimentalFactor record with same name: 'unknown'
→ returning existing Tissue record with same name: 'unknown'
→ returning existing DevelopmentalStage record with same name: 'unknown'
→ returning existing Disease record with same name: 'normal'
→ returning existing Disease record with same name: 'unknown'

In [4]:
import bionty as bt
bt.Organism.filter().df()

,uid,name,ontology_id,scientific_name,synonyms,description,space_id,source_id,run_id,created_at,created_by_id,_aux,_branch_code
id,,,,,,,,,,,,,
1,3RZqbcSL,mouse,NCBITaxon:10090,mus_musculus,None,None,1,5.0,None,2024-12-13 02:25:45.687370+00:00,1,None,1
2,1dpCL6Td,human,NCBITaxon:9606,homo_sapiens,None,None,1,5.0,None,2024-12-13 02:25:45.687409+00:00,1,None,1
3,5HWRj1OD,unknown,unknown,None,None,None,1,NaN,None,2024-12-13 02:25:45.691921+00:00,1,None,1

In [2]:
hgenedf = load_genes(organisms="NCBITaxon:9606")
hgenedf

,uid,symbol,ncbi_gene_ids,biotype,synonyms,description,organism_id,mt,ribo,hb,organism
ensembl_gene_id,,,,,,,,,,,
ENSG00000000003,1uTi9dROoaN5,TSPAN6,7105,protein_coding,TSPAN-6|T245|TM4SF6,tetraspanin 6,2,False,False,False,NCBITaxon:9606
ENSG00000000005,2FhduD7Z97Uv,TNMD,64102,protein_coding,TEM|MYODULIN|CHM1L|TENDIN|BRICD4,tenomodulin,2,False,False,False,NCBITaxon:9606
ENSG00000000419,4eC1wUNJAO2s,DPM1,8813,protein_coding,CDGIE|MPDS,dolichyl-phosphate mannosyltransferase subunit...,2,False,False,False,NCBITaxon:9606
ENSG00000000457,5Zug63FETk4p,SCYL3,57147,protein_coding,PACE1|PACE-1,SCY1 like pseudokinase 3,2,False,False,False,NCBITaxon:9606
ENSG00000000460,3wEqb6eOTZzC,FIRRM,55732,protein_coding,C1ORF112|FLJ10706|APOLO1|FLIP|MEICA1,FIGNL1 interacting regulator of recombination ...,2,False,False,False,NCBITaxon:9606
...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000293596,42lwxhgTHxaN,None,105372654,lncRNA,,novel transcript,2,False,False,False,NCBITaxon:9606
ENSG00000293597,12nPu7ce9hLZ,LINC00970,101978719,lncRNA,,long intergenic non-protein coding RNA 970,2,False,False,False,NCBITaxon:9606
ENSG00000293599,2DLKDsGV0zX9,None,,lncRNA,,novel transcript,2,False,False,False,NCBITaxon:9606
ENSG00000293600,7hbNrFh6GVRt,None,131768270,protein_coding,,novel protein,2,False,False,False,NCBITaxon:9606
ENSG00000293604,43PKjUN2TuRj,ORAI1,84876,protein_coding,TMEM142A|CRACM1|FLJ14466,ORAI calcium release-activated calcium modulat...,2,False,False,False,NCBITaxon:9606

### 修改尝试

In [13]:
from pathlib import Path
from esm.utils.constants.esm3 import data_root

# 指定模型路径
path = Path("../temp/data/models--EvolutionaryScale--esmc-600m-2024-12")

# 检查路径是否存在
if not path.exists():
    raise FileNotFoundError(f"Model files not found at: {path}")

# 打印路径
print(f"Model path: {path}")

Model path: ../temp/data/models--EvolutionaryScale--esmc-600m-2024-12

In [7]:
#OF NOTE: 这是原版
import os

import pandas as pd
import torch

# from RNABERT import RNABERT
from torch.nn import AdaptiveAvgPool1d

from scprint import utils

from scprint.tokenizers.protein_embedder import ESM2
from tqdm import tqdm
import numpy as np


def protein_embeddings_generator(
    genedf: pd.DataFrame = None,
    organism: str = "homo_sapiens",  # mus_musculus,
    cache: bool = True,
    fasta_path: str = "/tmp/data/fasta/",
    embedding_size: int = 512,
    embedder: str = "esm3",  # or glm2
    cuda: bool = True,
):
    """
    protein_embeddings_generator embed a set of genes using fasta file and LLMs

    Args:
        genedf (pd.DataFrame): A DataFrame containing gene information.
        organism (str, optional): The organism to which the genes belong. Defaults to "homo_sapiens".
        cache (bool, optional): If True, the function will use cached data if available. Defaults to True.
        fasta_path (str, optional): The path to the directory where the fasta files are stored. Defaults to "/tmp/data/fasta/".
        embedding_size (int, optional): The size of the embeddings to be generated. Defaults to 512.
    Returns:
        pd.DataFrame: Returns a DataFrame containing the protein embeddings.
        pd.DataFrame: Returns the naming dataframe.
    """
    # given a gene file and organism
    # load the organism fasta if not already done
    fasta_path_pep, fasta_path_ncrna = utils.load_fasta_species(
        species=organism, output_path=fasta_path, cache=cache
    )
    # subset the fasta
    fasta_name = fasta_path_pep.split("/")[-1]
    utils.utils.run_command(["gunzip", fasta_path_pep])
    protgenedf = (
        genedf[genedf["biotype"] == "protein_coding"] if genedf is not None else None
    )
    found, naming_df = utils.subset_fasta(
        protgenedf.index.tolist() if protgenedf is not None else None,
        subfasta_path=fasta_path + "subset.fa",
        fasta_path=fasta_path + fasta_name[:-3],
        drop_unknown_seq=True,
    )
    if embedder == "esm2":
        prot_embedder = ESM2()
        prot_embeddings = prot_embedder(
            fasta_path + "subset.fa", output_folder=fasta_path + "esm_out/", cache=cache
        )
    elif embedder == "esm3":
        from esm.models.esmc import ESMC
        from esm.sdk.api import ESMProtein, LogitsConfig
        from Bio import SeqIO

        prot_embeddings = []
        names = []
        client = ESMC.from_pretrained("esmc_600m").to("cuda" if cuda else "cpu")
        conf = LogitsConfig(sequence=True, return_embeddings=True)
        with (
            open(fasta_path + "subset.fa", "r") as fasta,
        ):
            for record in tqdm(SeqIO.parse(fasta, "fasta")):
                protein = ESMProtein(sequence=str(record.seq))
                protein_tensor = client.encode(protein)
                logits_output = client.logits(protein_tensor, conf)
                prot_embeddings.append(
                    logits_output.embeddings[0].mean(0).cpu().numpy().tolist()
                )
                names.append(record.id)
    else:
        raise ValueError(f"Embedder {embedder} not supported")
    # load the data and erase / zip the rest
    # utils.utils.run_command(["gzip", fasta_path + fasta_name[:-3]])
    # return the embedding and gene file
    # TODO: to redebug
    # do the same for RNA
    # rnagenedf = genedf[genedf["biotype"] != "protein_coding"]
    # fasta_file = next(
    #    file for file in os.listdir(fasta_path) if file.endswith(".ncrna.fa.gz")
    # )
    # utils.utils.run_command(["gunzip", fasta_path + fasta_file])
    # utils.subset_fasta(
    #    rnagenedf["ensembl_gene_id"].tolist(),
    #    subfasta_path=fasta_path + "subset.ncrna.fa",
    #    fasta_path=fasta_path + fasta_file[:-3],
    #    drop_unknown_seq=True,
    # )
    # rna_embedder = RNABERT()
    # rna_embeddings = rna_embedder(fasta_path + "subset.ncrna.fa")
    ## Check if the sizes of the cembeddings are not the same
    # utils.utils.run_command(["gzip", fasta_path + fasta_file[:-3]])
    #
    m = AdaptiveAvgPool1d(embedding_size)
    prot_embeddings = pd.DataFrame(
        data=m(torch.tensor(np.array(prot_embeddings))), index=names
    )
    # rna_embeddings = pd.DataFrame(
    #    data=m(torch.tensor(rna_embeddings.values)), index=rna_embeddings.index
    # )
    # Concatenate the embeddings
    return prot_embeddings, naming_df  # pd.concat([prot_embeddings, rna_embeddings])

In [3]:
##OF NOTE: 这是自己的修订版
import os

import pandas as pd
import torch

# from RNABERT import RNABERT
from torch.nn import AdaptiveAvgPool1d

from scprint import utils

from scprint.tokenizers.protein_embedder import ESM2
from tqdm import tqdm
import numpy as np
from transformers import AutoConfig
from transformers import AutoTokenizer
from esm.pretrained import load_local_model

def protein_embeddings_generator(
    genedf: pd.DataFrame = None,
    organism: str = "homo_sapiens",  # mus_musculus,
    cache: bool = True,
    fasta_path: str = "/tmp/data/fasta/",
    embedding_size: int = 512,
    embedder: str = "esm3",  # or glm2
    cuda: bool = True,
):
    """
    protein_embeddings_generator embed a set of genes using fasta file and LLMs

    Args:
        genedf (pd.DataFrame): A DataFrame containing gene information.
        organism (str, optional): The organism to which the genes belong. Defaults to "homo_sapiens".
        cache (bool, optional): If True, the function will use cached data if available. Defaults to True.
        fasta_path (str, optional): The path to the directory where the fasta files are stored. Defaults to "/tmp/data/fasta/".
        embedding_size (int, optional): The size of the embeddings to be generated. Defaults to 512.
    Returns:
        pd.DataFrame: Returns a DataFrame containing the protein embeddings.
        pd.DataFrame: Returns the naming dataframe.
    """
    # given a gene file and organism
    # load the organism fasta if not already done
    fasta_path_pep, fasta_path_ncrna = utils.load_fasta_species(
        species=organism, output_path=fasta_path, cache=cache
    )
    # subset the fasta
    fasta_name = fasta_path_pep.split("/")[-1]
    utils.utils.run_command(["gunzip", fasta_path_pep])
    protgenedf = (
        genedf[genedf["biotype"] == "protein_coding"] if genedf is not None else None
    )
    found, naming_df = utils.subset_fasta(
        protgenedf.index.tolist() if protgenedf is not None else None,
        subfasta_path=fasta_path + "subset.fa",
        fasta_path=fasta_path + fasta_name[:-3],
        drop_unknown_seq=True,
    )
    if embedder == "esm2":
        prot_embedder = ESM2()
        prot_embeddings = prot_embedder(
            fasta_path + "subset.fa", output_folder=fasta_path + "esm_out/", cache=cache
        )
    elif embedder == "esm3":
        from esm.models.esmc import ESMC
        from esm.sdk.api import ESMProtein, LogitsConfig
        from Bio import SeqIO

        prot_embeddings = []
        names = []
        
        # 手动指定本地权重文件的路径
        local_weights_path = "/disk2/044/scprint/temp/data/esmc-600m-2024-12/data/weights/esmc_600m_2024_12_v0.pth"
        try:
            client = load_local_model(
            "esmc_600m",
            device="cuda" if cuda else "cpu"
            )
            # 如果 load_local_model 无法直接加载权重，可以手动加载权重文件
            state_dict = torch.load(local_weights_path, map_location="cuda" if cuda else "cpu")
            client.load_state_dict(state_dict)
        except Exception as e:
            raise RuntimeError(f"无法加载本地模型：{e}")
            
        conf = LogitsConfig(sequence=True, return_embeddings=True)
        with (
            open(fasta_path + "subset.fa", "r") as fasta,
        ):
            for record in tqdm(SeqIO.parse(fasta, "fasta")):
                protein = ESMProtein(sequence=str(record.seq))
                protein_tensor = client.encode(protein)
                logits_output = client.logits(protein_tensor, conf)
                prot_embeddings.append(
                    logits_output.embeddings[0].mean(0).cpu().numpy().tolist()
                )
                names.append(record.id)
    else:
        raise ValueError(f"Embedder {embedder} not supported")
    # load the data and erase / zip the rest
    # utils.utils.run_command(["gzip", fasta_path + fasta_name[:-3]])
    # return the embedding and gene file
    # TODO: to redebug
    # do the same for RNA
    # rnagenedf = genedf[genedf["biotype"] != "protein_coding"]
    # fasta_file = next(
    #    file for file in os.listdir(fasta_path) if file.endswith(".ncrna.fa.gz")
    # )
    # utils.utils.run_command(["gunzip", fasta_path + fasta_file])
    # utils.subset_fasta(
    #    rnagenedf["ensembl_gene_id"].tolist(),
    #    subfasta_path=fasta_path + "subset.ncrna.fa",
    #    fasta_path=fasta_path + fasta_file[:-3],
    #    drop_unknown_seq=True,
    # )
    # rna_embedder = RNABERT()
    # rna_embeddings = rna_embedder(fasta_path + "subset.ncrna.fa")
    ## Check if the sizes of the cembeddings are not the same
    # utils.utils.run_command(["gzip", fasta_path + fasta_file[:-3]])
    #
    m = AdaptiveAvgPool1d(embedding_size)
    prot_embeddings = pd.DataFrame(
        data=m(torch.tensor(np.array(prot_embeddings))), index=names
    )
    # rna_embeddings = pd.DataFrame(
    #    data=m(torch.tensor(rna_embeddings.values)), index=rna_embeddings.index
    # )
    # Concatenate the embeddings
    return prot_embeddings, naming_df  # pd.concat([prot_embeddings, rna_embeddings])

In [8]:
from pathlib import Path

def data_root(model):
    """
    Returns the root directory for the specified model.

    Args:
        model (str): The model name (e.g., "esmc-600m").

    Returns:
        Path: The path to the model directory.
    """
    if model.startswith("esmc-300"):
        return Path("/path/to/local/esmc-300m")
    elif model.startswith("esmc-600"):
        return Path("/disk2/044/scprint/temp/data/esmc-600m-2024-12")
    else:
        raise ValueError(f"{model=} is an invalid model name.")

In [3]:
!export HF_ENDPOINT=https://hf-mirror.com

In [4]:
import os
os.environ['HF_ENDPOINT'] = 'https://hf-mirror.com'

In [3]:
from huggingface_hub import HfApi

api = HfApi(endpoint="https://hf-mirror.com")
repo_info = api.repo_info(repo_id="EvolutionaryScale/esmc-600m-2024-12", revision="main")

In [2]:
from huggingface_hub import notebook_login

notebook_login("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")
#如果是镜像网站的话  不能登录的

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [40]:
# 确保安装了最新版本的 huggingface_hub
# !pip install --upgrade huggingface_hub

from huggingface_hub import login, whoami

# 方法 1: 使用 notebook_login 并手动输入 Token
# notebook_login()

# 方法 2: 直接在代码中使用 Token 登录
token = "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"  # 替换为您的实际 Token

try:
    login(token=token)
    user = whoami()
    print(f"当前登录用户: {user}")
except Exception as e:
    print(f"登录失败: {e}")

In [10]:
print(data_root("esmc-600") / "data/weights/esmc_600m_2024_12_v0.pth")

NameError: name 'data_root' is not defined

### 正式开始

In [3]:
##OF NOTE: 这是自己的修订版
import os

import pandas as pd
import torch

# from RNABERT import RNABERT
from torch.nn import AdaptiveAvgPool1d

from scprint import utils

from scprint.tokenizers.protein_embedder import ESM2
from tqdm import tqdm
import numpy as np
from transformers import AutoConfig
from transformers import AutoTokenizer
from esm.pretrained import load_local_model

def protein_embeddings_generator(
    genedf: pd.DataFrame = None,
    organism: str = "homo_sapiens",  # mus_musculus,
    cache: bool = True,
    fasta_path: str = "/tmp/data/fasta/",
    embedding_size: int = 512,
    embedder: str = "esm3",  # or glm2
    cuda: bool = True,
):
    """
    protein_embeddings_generator embed a set of genes using fasta file and LLMs

    Args:
        genedf (pd.DataFrame): A DataFrame containing gene information.
        organism (str, optional): The organism to which the genes belong. Defaults to "homo_sapiens".
        cache (bool, optional): If True, the function will use cached data if available. Defaults to True.
        fasta_path (str, optional): The path to the directory where the fasta files are stored. Defaults to "/tmp/data/fasta/".
        embedding_size (int, optional): The size of the embeddings to be generated. Defaults to 512.
    Returns:
        pd.DataFrame: Returns a DataFrame containing the protein embeddings.
        pd.DataFrame: Returns the naming dataframe.
    """
    # given a gene file and organism
    # load the organism fasta if not already done
    fasta_path_pep, fasta_path_ncrna = utils.load_fasta_species(
        species=organism, output_path=fasta_path, cache=cache
    )
    # subset the fasta
    fasta_name = fasta_path_pep.split("/")[-1]
    utils.utils.run_command(["gunzip", fasta_path_pep])
    protgenedf = (
        genedf[genedf["biotype"] == "protein_coding"] if genedf is not None else None
    )
    found, naming_df = utils.subset_fasta(
        protgenedf.index.tolist() if protgenedf is not None else None,
        subfasta_path=fasta_path + "subset.fa",
        fasta_path=fasta_path + fasta_name[:-3],
        drop_unknown_seq=True,
    )
    if embedder == "esm2":
        prot_embedder = ESM2()
        prot_embeddings = prot_embedder(
            fasta_path + "subset.fa", output_folder=fasta_path + "esm_out/", cache=cache
        )
    elif embedder == "esm3":
        from esm.models.esmc import ESMC
        from esm.sdk.api import ESMProtein, LogitsConfig
        from Bio import SeqIO

        prot_embeddings = []
        names = []
        
        # 手动指定本地权重文件的路径
        local_weights_path = "/disk2/044/scprint/temp/data/esmc-600m-2024-12/data/weights/esmc_600m_2024_12_v0.pth"
        try:
            client = load_local_model(
            "esmc_600m",
            device="cuda" if cuda else "cpu"
            )
            # 如果 load_local_model 无法直接加载权重，可以手动加载权重文件
            state_dict = torch.load(local_weights_path, map_location="cuda" if cuda else "cpu")
            client.load_state_dict(state_dict)
        except Exception as e:
            raise RuntimeError(f"无法加载本地模型：{e}")
            
        conf = LogitsConfig(sequence=True, return_embeddings=True)
        with (
            open(fasta_path + "subset.fa", "r") as fasta,
        ):
            for record in tqdm(SeqIO.parse(fasta, "fasta")):
                protein = ESMProtein(sequence=str(record.seq))
                protein_tensor = client.encode(protein)
                logits_output = client.logits(protein_tensor, conf)
                prot_embeddings.append(
                    logits_output.embeddings[0].mean(0).cpu().numpy().tolist()
                )
                names.append(record.id)
    else:
        raise ValueError(f"Embedder {embedder} not supported")
    # load the data and erase / zip the rest
    # utils.utils.run_command(["gzip", fasta_path + fasta_name[:-3]])
    # return the embedding and gene file
    # TODO: to redebug
    # do the same for RNA
    # rnagenedf = genedf[genedf["biotype"] != "protein_coding"]
    # fasta_file = next(
    #    file for file in os.listdir(fasta_path) if file.endswith(".ncrna.fa.gz")
    # )
    # utils.utils.run_command(["gunzip", fasta_path + fasta_file])
    # utils.subset_fasta(
    #    rnagenedf["ensembl_gene_id"].tolist(),
    #    subfasta_path=fasta_path + "subset.ncrna.fa",
    #    fasta_path=fasta_path + fasta_file[:-3],
    #    drop_unknown_seq=True,
    # )
    # rna_embedder = RNABERT()
    # rna_embeddings = rna_embedder(fasta_path + "subset.ncrna.fa")
    ## Check if the sizes of the cembeddings are not the same
    # utils.utils.run_command(["gzip", fasta_path + fasta_file[:-3]])
    #
    m = AdaptiveAvgPool1d(embedding_size)
    prot_embeddings = pd.DataFrame(
        data=m(torch.tensor(np.array(prot_embeddings))), index=names
    )
    # rna_embeddings = pd.DataFrame(
    #    data=m(torch.tensor(rna_embeddings.values)), index=rna_embeddings.index
    # )
    # Concatenate the embeddings
    return prot_embeddings, naming_df  # pd.concat([prot_embeddings, rna_embeddings])

In [4]:
#rm -r "/tmp/data/fasta/"
homo_emb = protein_embeddings_generator(hgenedf, organism="homo_sapiens", cache=False, embedder="esm3", embedding_size=1024, fasta_path = "../temp/data/fasta/",)
#会自动下载模型 难道要挂VPN?
#试着自己下载模型 然后修改函数之后本地加载  太麻烦了吧

gzip: ../temp/data/fasta/Homo_sapiens.GRCh38.pep.all.fa already exists;	not overwritten

18017  genes had duplicates
dropped 112 weird sequences

20676it [20:06, 17.14it/s]

OutOfMemoryError: CUDA out of memory. Tried to allocate 2.08 GiB. GPU 0 has a total capacity of 11.76 GiB of which 1.42 GiB is free. Including non-PyTorch memory, this process has 10.33 GiB memory in use. Of the allocated memory 8.12 GiB is allocated by PyTorch, and 2.08 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

解决方法：
1. 使用镜像网站 好像不太行
2. 本地下载之后修改代码读取模型 好像不太行 /disk2/044/scprint/temp/data/esmc-600m-2024-12/data/weights/esmc_600m_2024_12_v0.pth
3. 是否需要登录账号再用原来的网站下载？

方法二的修改：
1. 修改 data_root 路径：
2. 修改 ESMC.from_pretrained 的调用

In [7]:
homo_emb.to_parquet("homo_emb.parquet")

# mouse

In [3]:
mgenedf = load_genes(organisms="NCBITaxon:10090")

In [5]:
#rm -r "/tmp/data/fasta/"
mouse_emb = protein_embeddings_generator(mgenedf, organism="mus_musculus", cache=False, embedding_size=1024)

/home/ml4ig1/Documents code/scPRINT/scprint/loaders/embedder.py:39: ResourceWarning: unclosed file <_io.BufferedReader name=107>
  utils.utils.run_command(["gunzip", fasta_path + fasta_file])
ResourceWarning: Enable tracemalloc to get the object allocation traceback

15073  genes had duplicates
dropped 97 weird sequences
running protbert
b'Transferred model to GPU'
b'Read /tmp/data/fasta/subset.fa with 21607 sequences'
b'Processing 1 of 2950 batches (117 sequences)'
b'Processing 2 of 2950 batches (89 sequences)'
b'Processing 3 of 2950 batches (78 sequences)'
b'Processing 4 of 2950 batches (71 sequences)'
b'Processing 5 of 2950 batches (67 sequences)'
b'Processing 6 of 2950 batches (63 sequences)'
b'Processing 7 of 2950 batches (59 sequences)'
b'Processing 8 of 2950 batches (57 sequences)'
b'Processing 9 of 2950 batches (55 sequences)'
b'Processing 10 of 2950 batches (53 sequences)'
b'Processing 11 of 2950 batches (52 sequences)'
b'Processing 12 of 2950 batches (51 sequences)'
b'Processing 13 of 2950 batches (49 sequences)'
b'Processing 14 of 2950 batches (48 sequences)'
b'Processing 15 of 2950 batches (47 sequences)'
b'Processing 16 of 2950 batches (46 sequences)'
b'Processing 17 of 2950 batches (46 sequences)'
b'Processing 18 of 2950 batches (45 sequences)'
b'Processing 19 of 2950 batches (44 sequences)'
b'Processing 20 of 2950 batches (43 sequences)'
b'Processing 21 of 2950 batches (42 sequences)'
b'Processing 22 of 2950 batches (42 sequences)'
b'Processing 23 of 2950 batches (41 sequences)'
b'Processing 24 of 2950 batches (41 sequences)'
b'Processing 25 of 2950 batches (40 sequences)'
b'Processing 26 of 2950 batches (40 sequences)'
b'Processing 27 of 2950 batches (39 sequences)'
b'Processing 28 of 2950 batches (39 sequences)'
b'Processing 29 of 2950 batches (38 sequences)'
b'Processing 30 of 2950 batches (38 sequences)'
b'Processing 31 of 2950 batches (37 sequences)'
b'Processing 32 of 2950 batches (37 sequences)'
b'Processing 33 of 2950 batches (36 sequences)'
b'Processing 34 of 2950 batches (36 sequences)'
b'Processing 35 of 2950 batches (36 sequences)'
b'Processing 36 of 2950 batches (35 sequences)'
b'Processing 37 of 2950 batches (35 sequences)'
b'Processing 38 of 2950 batches (35 sequences)'
b'Processing 39 of 2950 batches (34 sequences)'
b'Processing 40 of 2950 batches (34 sequences)'
b'Processing 41 of 2950 batches (34 sequences)'
b'Processing 42 of 2950 batches (33 sequences)'
b'Processing 43 of 2950 batches (33 sequences)'
b'Processing 44 of 2950 batches (33 sequences)'
b'Processing 45 of 2950 batches (32 sequences)'
b'Processing 46 of 2950 batches (32 sequences)'
b'Processing 47 of 2950 batches (32 sequences)'
b'Processing 48 of 2950 batches (32 sequences)'
b'Processing 49 of 2950 batches (31 sequences)'
b'Processing 50 of 2950 batches (31 sequences)'
b'Processing 51 of 2950 batches (31 sequences)'
b'Processing 52 of 2950 batches (31 sequences)'
b'Processing 53 of 2950 batches (31 sequences)'
b'Processing 54 of 2950 batches (30 sequences)'
b'Processing 55 of 2950 batches (30 sequences)'
b'Processing 56 of 2950 batches (30 sequences)'
b'Processing 57 of 2950 batches (30 sequences)'
b'Processing 58 of 2950 batches (29 sequences)'
b'Processing 59 of 2950 batches (29 sequences)'
b'Processing 60 of 2950 batches (29 sequences)'
b'Processing 61 of 2950 batches (29 sequences)'
b'Processing 62 of 2950 batches (29 sequences)'
b'Processing 63 of 2950 batches (29 sequences)'
b'Processing 64 of 2950 batches (28 sequences)'
b'Processing 65 of 2950 batches (28 sequences)'
b'Processing 66 of 2950 batches (28 sequences)'
b'Processing 67 of 2950 batches (28 sequences)'
b'Processing 68 of 2950 batches (28 sequences)'
b'Processing 69 of 2950 batches (28 sequences)'
b'Processing 70 of 2950 batches (27 sequences)'
b'Processing 71 of 2950 batches (27 sequences)'
b'Processing 72 of 2950 batches (27 sequences)'
b'Processing 73 of 2950 batches (27 sequences)'
b'Processing 74 of 2950 batches (27 sequences)'
b'Processing 75 of 2950 batches (27 sequences)'
b'Processing 76 of 2950 batches (27 sequences)'
b'Processing 77 of 2950 batches (26 sequences)'
b'Processing 78 of 2950 batches (26 sequences)'
b'Processing 79 of 2950 batches (26 sequences)'
b'Processing 80 of 2950 batches (26 sequences)'
b'Processing 81 of 2950 batches (26 sequences)'
b'Processing 82 of 2950 batches (26 sequences)'
b'Processing 83 of 2950 batches (26 sequences)'
b'Processing 84 of 2950 batches (25 sequences)'
b'Processing 85 of 2950 batches (25 sequences)'
b'Processing 86 of 2950 batches (25 sequences)'
b'Processing 87 of 2950 batches (25 sequences)'
b'Processing 88 of 2950 batches (25 sequences)'
b'Processing 89 of 2950 batches (25 sequences)'
b'Processing 90 of 2950 batches (25 sequences)'
b'Processing 91 of 2950 batches (24 sequences)'
b'Processing 92 of 2950 batches (24 sequences)'
b'Processing 93 of 2950 batches (24 sequences)'
b'Processing 94 of 2950 batches (24 sequences)'
b'Processing 95 of 2950 batches (24 sequences)'
b'Processing 96 of 2950 batches (24 sequences)'
b'Processing 97 of 2950 batches (24 sequences)'
b'Processing 98 of 2950 batches (24 sequences)'
b'Processing 99 of 2950 batches (24 sequences)'
b'Processing 100 of 2950 batches (23 sequences)'
b'Processing 101 of 2950 batches (23 sequences)'
b'Processing 102 of 2950 batches (23 sequences)'
b'Processing 103 of 2950 batches (23 sequences)'
b'Processing 104 of 2950 batches (23 sequences)'
b'Processing 105 of 2950 batches (23 sequences)'
b'Processing 106 of 2950 batches (23 sequences)'
b'Processing 107 of 2950 batches (23 sequences)'
b'Processing 108 of 2950 batches (23 sequences)'
b'Processing 109 of 2950 batches (23 sequences)'
b'Processing 110 of 2950 batches (23 sequences)'
b'Processing 111 of 2950 batches (23 sequences)'
b'Processing 112 of 2950 batches (22 sequences)'
b'Processing 113 of 2950 batches (22 sequences)'
b'Processing 114 of 2950 batches (22 sequences)'
b'Processing 115 of 2950 batches (22 sequences)'
b'Processing 116 of 2950 batches (22 sequences)'
b'Processing 117 of 2950 batches (22 sequences)'
b'Processing 118 of 2950 batches (22 sequences)'
b'Processing 119 of 2950 batches (22 sequences)'
b'Processing 120 of 2950 batches (22 sequences)'
b'Processing 121 of 2950 batches (22 sequences)'
b'Processing 122 of 2950 batches (22 sequences)'
b'Processing 123 of 2950 batches (22 sequences)'
b'Processing 124 of 2950 batches (22 sequences)'
b'Processing 125 of 2950 batches (21 sequences)'
b'Processing 126 of 2950 batches (21 sequences)'
b'Processing 127 of 2950 batches (21 sequences)'
b'Processing 128 of 2950 batches (21 sequences)'
b'Processing 129 of 2950 batches (21 sequences)'
b'Processing 130 of 2950 batches (21 sequences)'
b'Processing 131 of 2950 batches (21 sequences)'
b'Processing 132 of 2950 batches (21 sequences)'
b'Processing 133 of 2950 batches (21 sequences)'
b'Processing 134 of 2950 batches (21 sequences)'
b'Processing 135 of 2950 batches (21 sequences)'
b'Processing 136 of 2950 batches (21 sequences)'
b'Processing 137 of 2950 batches (21 sequences)'
b'Processing 138 of 2950 batches (21 sequences)'
b'Processing 139 of 2950 batches (21 sequences)'
b'Processing 140 of 2950 batches (20 sequences)'
b'Processing 141 of 2950 batches (20 sequences)'
b'Processing 142 of 2950 batches (20 sequences)'
b'Processing 143 of 2950 batches (20 sequences)'
b'Processing 144 of 2950 batches (20 sequences)'
b'Processing 145 of 2950 batches (20 sequences)'
b'Processing 146 of 2950 batches (20 sequences)'
b'Processing 147 of 2950 batches (20 sequences)'
b'Processing 148 of 2950 batches (20 sequences)'
b'Processing 149 of 2950 batches (20 sequences)'
b'Processing 150 of 2950 batches (20 sequences)'
b'Processing 151 of 2950 batches (20 sequences)'
b'Processing 152 of 2950 batches (20 sequences)'
b'Processing 153 of 2950 batches (20 sequences)'
b'Processing 154 of 2950 batches (20 sequences)'
b'Processing 155 of 2950 batches (19 sequences)'
b'Processing 156 of 2950 batches (19 sequences)'
b'Processing 157 of 2950 batches (19 sequences)'
b'Processing 158 of 2950 batches (19 sequences)'
b'Processing 159 of 2950 batches (19 sequences)'
b'Processing 160 of 2950 batches (19 sequences)'
b'Processing 161 of 2950 batches (19 sequences)'
b'Processing 162 of 2950 batches (19 sequences)'
b'Processing 163 of 2950 batches (19 sequences)'
b'Processing 164 of 2950 batches (19 sequences)'
b'Processing 165 of 2950 batches (19 sequences)'
b'Processing 166 of 2950 batches (19 sequences)'
b'Processing 167 of 2950 batches (19 sequences)'
b'Processing 168 of 2950 batches (19 sequences)'
b'Processing 169 of 2950 batches (19 sequences)'
b'Processing 170 of 2950 batches (19 sequences)'
b'Processing 171 of 2950 batches (19 sequences)'
b'Processing 172 of 2950 batches (19 sequences)'
b'Processing 173 of 2950 batches (19 sequences)'
b'Processing 174 of 2950 batches (19 sequences)'
b'Processing 175 of 2950 batches (19 sequences)'
b'Processing 176 of 2950 batches (19 sequences)'
b'Processing 177 of 2950 batches (18 sequences)'
b'Processing 178 of 2950 batches (18 sequences)'
b'Processing 179 of 2950 batches (18 sequences)'
b'Processing 180 of 2950 batches (18 sequences)'
b'Processing 181 of 2950 batches (18 sequences)'
b'Processing 182 of 2950 batches (18 sequences)'
b'Processing 183 of 2950 batches (18 sequences)'
b'Processing 184 of 2950 batches (18 sequences)'
b'Processing 185 of 2950 batches (18 sequences)'
b'Processing 186 of 2950 batches (18 sequences)'
b'Processing 187 of 2950 batches (18 sequences)'
b'Processing 188 of 2950 batches (18 sequences)'
b'Processing 189 of 2950 batches (18 sequences)'
b'Processing 190 of 2950 batches (18 sequences)'
b'Processing 191 of 2950 batches (18 sequences)'
b'Processing 192 of 2950 batches (18 sequences)'
b'Processing 193 of 2950 batches (18 sequences)'
b'Processing 194 of 2950 batches (18 sequences)'
b'Processing 195 of 2950 batches (18 sequences)'
b'Processing 196 of 2950 batches (18 sequences)'
b'Processing 197 of 2950 batches (18 sequences)'
b'Processing 198 of 2950 batches (18 sequences)'
b'Processing 199 of 2950 batches (18 sequences)'
b'Processing 200 of 2950 batches (18 sequences)'
b'Processing 201 of 2950 batches (18 sequences)'
b'Processing 202 of 2950 batches (18 sequences)'
b'Processing 203 of 2950 batches (17 sequences)'
b'Processing 204 of 2950 batches (17 sequences)'
b'Processing 205 of 2950 batches (17 sequences)'
b'Processing 206 of 2950 batches (17 sequences)'
b'Processing 207 of 2950 batches (17 sequences)'
b'Processing 208 of 2950 batches (17 sequences)'
b'Processing 209 of 2950 batches (17 sequences)'
b'Processing 210 of 2950 batches (17 sequences)'
b'Processing 211 of 2950 batches (17 sequences)'
b'Processing 212 of 2950 batches (17 sequences)'
b'Processing 213 of 2950 batches (17 sequences)'
b'Processing 214 of 2950 batches (17 sequences)'
b'Processing 215 of 2950 batches (17 sequences)'
b'Processing 216 of 2950 batches (17 sequences)'
b'Processing 217 of 2950 batches (17 sequences)'
b'Processing 218 of 2950 batches (17 sequences)'
b'Processing 219 of 2950 batches (17 sequences)'
b'Processing 220 of 2950 batches (17 sequences)'
b'Processing 221 of 2950 batches (17 sequences)'
b'Processing 222 of 2950 batches (17 sequences)'
b'Processing 223 of 2950 batches (17 sequences)'
b'Processing 224 of 2950 batches (17 sequences)'
b'Processing 225 of 2950 batches (17 sequences)'
b'Processing 226 of 2950 batches (17 sequences)'
b'Processing 227 of 2950 batches (17 sequences)'
b'Processing 228 of 2950 batches (17 sequences)'
b'Processing 229 of 2950 batches (17 sequences)'
b'Processing 230 of 2950 batches (16 sequences)'
b'Processing 231 of 2950 batches (16 sequences)'
b'Processing 232 of 2950 batches (16 sequences)'
b'Processing 233 of 2950 batches (16 sequences)'
b'Processing 234 of 2950 batches (16 sequences)'
b'Processing 235 of 2950 batches (16 sequences)'
b'Processing 236 of 2950 batches (16 sequences)'
b'Processing 237 of 2950 batches (16 sequences)'
b'Processing 238 of 2950 batches (16 sequences)'
b'Processing 239 of 2950 batches (16 sequences)'
b'Processing 240 of 2950 batches (16 sequences)'
b'Processing 241 of 2950 batches (16 sequences)'
b'Processing 242 of 2950 batches (16 sequences)'
b'Processing 243 of 2950 batches (16 sequences)'
b'Processing 244 of 2950 batches (16 sequences)'
b'Processing 245 of 2950 batches (16 sequences)'
b'Processing 246 of 2950 batches (16 sequences)'
b'Processing 247 of 2950 batches (16 sequences)'
b'Processing 248 of 2950 batches (16 sequences)'
b'Processing 249 of 2950 batches (16 sequences)'
b'Processing 250 of 2950 batches (16 sequences)'
b'Processing 251 of 2950 batches (16 sequences)'
b'Processing 252 of 2950 batches (16 sequences)'
b'Processing 253 of 2950 batches (16 sequences)'
b'Processing 254 of 2950 batches (16 sequences)'
b'Processing 255 of 2950 batches (16 sequences)'
b'Processing 256 of 2950 batches (16 sequences)'
b'Processing 257 of 2950 batches (16 sequences)'
b'Processing 258 of 2950 batches (16 sequences)'
b'Processing 259 of 2950 batches (16 sequences)'
b'Processing 260 of 2950 batches (15 sequences)'
b'Processing 261 of 2950 batches (15 sequences)'
b'Processing 262 of 2950 batches (15 sequences)'
b'Processing 263 of 2950 batches (15 sequences)'
b'Processing 264 of 2950 batches (15 sequences)'
b'Processing 265 of 2950 batches (15 sequences)'
b'Processing 266 of 2950 batches (15 sequences)'
b'Processing 267 of 2950 batches (15 sequences)'
b'Processing 268 of 2950 batches (15 sequences)'
b'Processing 269 of 2950 batches (15 sequences)'
b'Processing 270 of 2950 batches (15 sequences)'
b'Processing 271 of 2950 batches (15 sequences)'
b'Processing 272 of 2950 batches (15 sequences)'
b'Processing 273 of 2950 batches (15 sequences)'
b'Processing 274 of 2950 batches (15 sequences)'
b'Processing 275 of 2950 batches (15 sequences)'
b'Processing 276 of 2950 batches (15 sequences)'
b'Processing 277 of 2950 batches (15 sequences)'
b'Processing 278 of 2950 batches (15 sequences)'
b'Processing 279 of 2950 batches (15 sequences)'
b'Processing 280 of 2950 batches (15 sequences)'
b'Processing 281 of 2950 batches (15 sequences)'
b'Processing 282 of 2950 batches (15 sequences)'
b'Processing 283 of 2950 batches (15 sequences)'
b'Processing 284 of 2950 batches (15 sequences)'
b'Processing 285 of 2950 batches (15 sequences)'
b'Processing 286 of 2950 batches (15 sequences)'
b'Processing 287 of 2950 batches (15 sequences)'
b'Processing 288 of 2950 batches (15 sequences)'
b'Processing 289 of 2950 batches (15 sequences)'
b'Processing 290 of 2950 batches (15 sequences)'
b'Processing 291 of 2950 batches (15 sequences)'
b'Processing 292 of 2950 batches (15 sequences)'
b'Processing 293 of 2950 batches (15 sequences)'
b'Processing 294 of 2950 batches (15 sequences)'
b'Processing 295 of 2950 batches (14 sequences)'
b'Processing 296 of 2950 batches (14 sequences)'
b'Processing 297 of 2950 batches (14 sequences)'
b'Processing 298 of 2950 batches (14 sequences)'
b'Processing 299 of 2950 batches (14 sequences)'
b'Processing 300 of 2950 batches (14 sequences)'
b'Processing 301 of 2950 batches (14 sequences)'
b'Processing 302 of 2950 batches (14 sequences)'
b'Processing 303 of 2950 batches (14 sequences)'
b'Processing 304 of 2950 batches (14 sequences)'
b'Processing 305 of 2950 batches (14 sequences)'
b'Processing 306 of 2950 batches (14 sequences)'
b'Processing 307 of 2950 batches (14 sequences)'
b'Processing 308 of 2950 batches (14 sequences)'
b'Processing 309 of 2950 batches (14 sequences)'
b'Processing 310 of 2950 batches (14 sequences)'
b'Processing 311 of 2950 batches (14 sequences)'
b'Processing 312 of 2950 batches (14 sequences)'
b'Processing 313 of 2950 batches (14 sequences)'
b'Processing 314 of 2950 batches (14 sequences)'
b'Processing 315 of 2950 batches (14 sequences)'
b'Processing 316 of 2950 batches (14 sequences)'
b'Processing 317 of 2950 batches (14 sequences)'
b'Processing 318 of 2950 batches (14 sequences)'
b'Processing 319 of 2950 batches (14 sequences)'
b'Processing 320 of 2950 batches (14 sequences)'
b'Processing 321 of 2950 batches (14 sequences)'
b'Processing 322 of 2950 batches (14 sequences)'
b'Processing 323 of 2950 batches (14 sequences)'
b'Processing 324 of 2950 batches (14 sequences)'
b'Processing 325 of 2950 batches (14 sequences)'
b'Processing 326 of 2950 batches (14 sequences)'
b'Processing 327 of 2950 batches (14 sequences)'
b'Processing 328 of 2950 batches (14 sequences)'
b'Processing 329 of 2950 batches (14 sequences)'
b'Processing 330 of 2950 batches (13 sequences)'
b'Processing 331 of 2950 batches (13 sequences)'
b'Processing 332 of 2950 batches (13 sequences)'
b'Processing 333 of 2950 batches (13 sequences)'
b'Processing 334 of 2950 batches (13 sequences)'
b'Processing 335 of 2950 batches (13 sequences)'
b'Processing 336 of 2950 batches (13 sequences)'
b'Processing 337 of 2950 batches (13 sequences)'
b'Processing 338 of 2950 batches (13 sequences)'
b'Processing 339 of 2950 batches (13 sequences)'
b'Processing 340 of 2950 batches (13 sequences)'
b'Processing 341 of 2950 batches (13 sequences)'
b'Processing 342 of 2950 batches (13 sequences)'
b'Processing 343 of 2950 batches (13 sequences)'
b'Processing 344 of 2950 batches (13 sequences)'
b'Processing 345 of 2950 batches (13 sequences)'
b'Processing 346 of 2950 batches (13 sequences)'
b'Processing 347 of 2950 batches (13 sequences)'
b'Processing 348 of 2950 batches (13 sequences)'
b'Processing 349 of 2950 batches (13 sequences)'
b'Processing 350 of 2950 batches (13 sequences)'
b'Processing 351 of 2950 batches (13 sequences)'
b'Processing 352 of 2950 batches (13 sequences)'
b'Processing 353 of 2950 batches (13 sequences)'
b'Processing 354 of 2950 batches (13 sequences)'
b'Processing 355 of 2950 batches (13 sequences)'
b'Processing 356 of 2950 batches (13 sequences)'
b'Processing 357 of 2950 batches (13 sequences)'
b'Processing 358 of 2950 batches (13 sequences)'
b'Processing 359 of 2950 batches (13 sequences)'
b'Processing 360 of 2950 batches (13 sequences)'
b'Processing 361 of 2950 batches (13 sequences)'
b'Processing 362 of 2950 batches (13 sequences)'
b'Processing 363 of 2950 batches (13 sequences)'
b'Processing 364 of 2950 batches (13 sequences)'
b'Processing 365 of 2950 batches (13 sequences)'
b'Processing 366 of 2950 batches (13 sequences)'
b'Processing 367 of 2950 batches (13 sequences)'
b'Processing 368 of 2950 batches (13 sequences)'
b'Processing 369 of 2950 batches (13 sequences)'
b'Processing 370 of 2950 batches (13 sequences)'
b'Processing 371 of 2950 batches (13 sequences)'
b'Processing 372 of 2950 batches (13 sequences)'
b'Processing 373 of 2950 batches (13 sequences)'
b'Processing 374 of 2950 batches (13 sequences)'
b'Processing 375 of 2950 batches (13 sequences)'
b'Processing 376 of 2950 batches (13 sequences)'
b'Processing 377 of 2950 batches (13 sequences)'
b'Processing 378 of 2950 batches (13 sequences)'
b'Processing 379 of 2950 batches (13 sequences)'
b'Processing 380 of 2950 batches (13 sequences)'
b'Processing 381 of 2950 batches (13 sequences)'
b'Processing 382 of 2950 batches (13 sequences)'
b'Processing 383 of 2950 batches (13 sequences)'
b'Processing 384 of 2950 batches (13 sequences)'
b'Processing 385 of 2950 batches (13 sequences)'
b'Processing 386 of 2950 batches (13 sequences)'
b'Processing 387 of 2950 batches (13 sequences)'
b'Processing 388 of 2950 batches (13 sequences)'
b'Processing 389 of 2950 batches (13 sequences)'
b'Processing 390 of 2950 batches (13 sequences)'
b'Processing 391 of 2950 batches (13 sequences)'
b'Processing 392 of 2950 batches (13 sequences)'
b'Processing 393 of 2950 batches (13 sequences)'
b'Processing 394 of 2950 batches (13 sequences)'
b'Processing 395 of 2950 batches (13 sequences)'
b'Processing 396 of 2950 batches (13 sequences)'
b'Processing 397 of 2950 batches (13 sequences)'
b'Processing 398 of 2950 batches (13 sequences)'
b'Processing 399 of 2950 batches (13 sequences)'
b'Processing 400 of 2950 batches (13 sequences)'
b'Processing 401 of 2950 batches (13 sequences)'
b'Processing 402 of 2950 batches (13 sequences)'
b'Processing 403 of 2950 batches (13 sequences)'
b'Processing 404 of 2950 batches (13 sequences)'
b'Processing 405 of 2950 batches (13 sequences)'
b'Processing 406 of 2950 batches (13 sequences)'
b'Processing 407 of 2950 batches (13 sequences)'

/home/ml4ig1/Documents code/scPRINT/scprint/loaders/protein_embedder.py:54: ResourceWarning: unclosed file <_io.BufferedReader name=107>
  run_command(cmd, shell=True)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/ml4ig1/Documents code/scPRINT/scprint/loaders/embedder.py:53: ResourceWarning: unclosed file <_io.BufferedReader name=107>
  utils.utils.run_command(["gzip", fasta_path + fasta_file[:-3]])
ResourceWarning: Enable tracemalloc to get the object allocation traceback

In [ ]:
mouse_emb.to_parquet("mouse_emb.parquet")

In [7]:
gene_emb = pd.concat([mouse_emb, homo_emb])
gene_emb.to_parquet("../data/main/gene_embeddings.parquet")

# Ovis_aries

# Macaca_mulatta

# generate gene location file

In [2]:
from scdataloader.utils import getBiomartTable

In [15]:
table = getBiomartTable(ensemble_server = "http://jan2024.archive.ensembl.org/biomart", database="hsapiens_gene_ensembl", attributes=['start_position', 'chromosome_name', 'ensembl_gene_id'], bypass_attributes=True).set_index('ensembl_gene_id') #mmusculus_gene_ensembl, hsapiens_gene_ensembl
table = table.loc[~table.index.duplicated(keep='first')]
table = table.sort_values(by=['chromosome_name', 'start_position'])
table

downloading gene names from biomart
['start_position', 'chromosome_name', 'ensembl_gene_id']

                 start_position chromosome_name
ensembl_gene_id
ENSG00000290825           11869               1
ENSG00000223972           12010               1
ENSG00000227232           14696               1
ENSG00000278267           17369               1
ENSG00000243485           29554               1
...                         ...             ...
ENSG00000292373        57184216               Y
ENSG00000292369        57190738               Y
ENSG00000292370        57201143               Y
ENSG00000292372        57207346               Y
ENSG00000292371        57212184               Y

[70611 rows x 2 columns]

In [9]:
from scdataloader import utils

In [11]:
a = utils.load_genes()

In [18]:
gene_position_tolerance = 10_000

In [19]:
c = []
i = 0
prev_position = -100_000
prev_chromosome = None
for _, r in table.iterrows():
    if (
        r["chromosome_name"] != prev_chromosome
        or r["start_position"] - prev_position > gene_position_tolerance
    ):
        i += 1
    c.append(i)
    prev_position = r["start_position"]
    prev_chromosome = r["chromosome_name"]
print(f"reduced the size to {len(set(c))/len(table)}")
table["pos"] = c

reduced the size to 0.6722574020195106

In [20]:
table2 = getBiomartTable(database="mmusculus_gene_ensembl", attributes=['start_position', 'chromosome_name']).set_index('ensembl_gene_id') #mmusculus_gene_ensembl, hsapiens_gene_ensembl
table2 = table2.loc[~table2.index.duplicated(keep='first')]
table2 = table2.sort_values(by=['chromosome_name', 'start_position'])
table2

downloading gene names from biomart
['ensembl_gene_id', 'hgnc_symbol', 'gene_biotype', 'entrezgene_id', 'start_position', 'chromosome_name']

,hgnc_symbol,gene_biotype,entrezgene_id,start_position,chromosome_name
ensembl_gene_id,,,,,
ENSMUSG00000102693,ENSMUSG00000102693,TEC,NaN,3143476,1
ENSMUSG00000064842,ENSMUSG00000064842,snRNA,115487594.0,3172239,1
ENSMUSG00000051951,ENSMUSG00000051951,protein_coding,497097.0,3276124,1
ENSMUSG00000102851,ENSMUSG00000102851,processed_pseudogene,NaN,3322980,1
ENSMUSG00000103377,ENSMUSG00000103377,TEC,NaN,3435954,1
...,...,...,...,...,...
ENSMUSG00000099399,ENSMUSG00000099399,lncRNA,NaN,90676615,Y
ENSMUSG00000095366,ENSMUSG00000095366,lncRNA,NaN,90763696,Y
ENSMUSG00000095134,ENSMUSG00000095134,unprocessed_pseudogene,NaN,90764326,Y
ENSMUSG00000096768,ENSMUSG00000096768,lncRNA,170942.0,90796007,Y
ENSMUSG00000099871,ENSMUSG00000099871,unprocessed_pseudogene,NaN,90848682,Y

In [21]:
c = []
i = 0
prev_position = -100000
prev_chromosome = None
for _, r in table2.iterrows():
    if (
        r["chromosome_name"] != prev_chromosome
        or r["start_position"] - prev_position > gene_position_tolerance
    ):
        i += 1
    c.append(i)
    prev_position = r["start_position"]
    prev_chromosome = r["chromosome_name"]
print(f"reduced the size to {len(set(c))/len(table2)}")
table2["pos"] = c

reduced the size to 0.7208162835215398

In [2]:
from scdataloader import utils

💡 connected lamindb: jkobject/scprint

In [5]:
import bionty as bt

In [10]:
bt.PublicSource.filter(
    entity="Phenotype",# source_website="pato"
)

In [13]:
bt.Phenotype.from_source(ontology_id="PATO:0000383")

Phenotype(uid='3OV8JZsS', name='female', ontology_id='PATO:0000383', description='A Biological Sex Quality Inhering In An Individual Or A Population That Only Produces Gametes That Can Be Fertilised By Male Gametes.', created_by_id=1, source_id=39, updated_at='2023-11-22 10:22:36 UTC')

In [26]:
bt.DevelopmentalStage.filter()[330:]

<QuerySet [DevelopmentalStage(uid='4yqONmUe', name='106-year-old human stage', ontology_id='HsapDv:0000234', description='Aged Stage That Refers To An Adult Who Is Over 106 And Under 107.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='2nBP50mg', name='first decade human stage', ontology_id='HsapDv:0000235', description='Human Stage That Refers To An Individual Who Is Over 0 And Under 10 Years Old.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='2lfFHRoz', name='second decade human stage', ontology_id='HsapDv:0000236', description='Human Stage That Refers To An Individual Who Is Over 10 And Under 20 Years Old.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='116jSpCp', name='tenth decade human stage', ontology_id='HsapDv:0000244', description='Human Stage That Refers To An Individual Who Is Over 90 And Under 100 Years Old.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='71UGWwZD', name='eleventh decade human stage', ontology_id='HsapDv:0000245', description='Human Stage That Refers To A Human Who Is Over 100 And Under 110 Years Old.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='3NMtboSP', name='centenarian human stage', ontology_id='HsapDv:0000247', description='Aged Stage That Refers To An Adult Who Is Over 100.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='4EQ5pZnH', name='107-year-old human stage', ontology_id='HsapDv:0000248', description='Aged Stage That Refers To An Adult Who Is Over 107 And Under 108.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='64wTuOyU', name='108-year-old human stage', ontology_id='HsapDv:0000249', description='Aged Stage That Refers To An Adult Who Is Over 108 And Under 109.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='2uWRGkaK', name='109-year-old human stage', ontology_id='HsapDv:0000250', description='Aged Stage That Refers To An Adult Who Is Over 109 And Under 110.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='2EPkljIU', name='110-year-old human stage', ontology_id='HsapDv:0000251', description='Aged Stage That Refers To An Adult Who Is Over 110 And Under 111.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='2JsDotoq', name='111-year-old human stage', ontology_id='HsapDv:0000252', description='Aged Stage That Refers To An Adult Who Is Over 111 And Under 112.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='lmvJZQde', name='112-year-old human stage', ontology_id='HsapDv:0000253', description='Aged Stage That Refers To An Adult Who Is Over 112 And Under 113.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='U0US2U4S', name='113-year-old human stage', ontology_id='HsapDv:0000254', description='Aged Stage That Refers To An Adult Who Is Over 113 And Under 114.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='7Pj1RpjN', name='114-year-old human stage', ontology_id='HsapDv:0000255', description='Aged Stage That Refers To An Adult Who Is Over 114 And Under 115.', created_by_id=1, source_id=44, updated_at='2023-11-28 12:55:35 UTC'), DevelopmentalStage(uid='7H4lnZbT', name='7 weeks', ontology_id='MmusDv:0000051', description='Early Adult Stage That Refers To A Mouse Which Is Over 49 Days And Under 57 Days Old.', created_by_id=1, source_id=45, updated_at='2024-03-20 20:46:33 UTC'), DevelopmentalStage(uid='1gCwII0u', name='8 weeks', ontology_id='MmusDv:0000052', description='2 Month-Old Stage That Refers To A Mouse Which Is Over 56 Days And Under 64 Days Old.', created_by_id=1, source_id=45, updated_at='2024-03-20 20:46:33 UTC'), DevelopmentalStage(uid='2xqsethz', name='9 weeks', ontology_id='MmusDv:0000053', description='2 Month-Old Stage That Refers To A Mouse Which Is Over 63 Days And Under 71 Days Old.', created_by_id=1, source_id=45, updated_at='2024-03-20 20:46:33 UTC'), DevelopmentalStage(uid='2ssAbReB', name='14 weeks', ontology_id='MmusDv:0000058', description='3 Month-Old Stage That Refers To A Mouse Which Is Over 98 Days And Under 106 Days Old.', created_by_id=1, source_id=45, updated_at='2024-03-20 20:46:34 UTC'), DevelopmentalStage(uid='7ArrXSuy', name='13 weeks', ontology_id='MmusDv:0000057', description='3 Month-Old Stage That Refers To A Mouse Which Is Over 91 Days And Under 99 Days Old.', created_by_id=1, source_id=45, updated_at='2024-03-20 20:46:33 UTC'), DevelopmentalStage(uid='5lY565b6', name='11 weeks', ontology_id='MmusDv:0000055', description='2 Month-Old Stage That Refers To A Mouse Which Is Over 77 Days And Under 85 Days Old.', created_by_id=1, source_id=45, updated_at='2024-03-20 20:46:33 UTC'), '...(remaining elements truncated)...']>

In [ ]:
bt.DevelopmentalStage.from_source

In [18]:
bionty_source = bt.public().filter(
    entity="DevelopmentalStage"
)

AttributeError: module 'bionty' has no attribute 'public'

In [4]:
utils.populate_my_ontology(
    organisms=["NCBITaxon:10090", "NCBITaxon:9606"],
    sex=["PATO:0000384", "PATO:0000383"],
    celltypes=None,
    ethnicities=None,
    assays=None,
    tissues=None,
    diseases=None,
    dev_stages=None,
)

💡 returning existing Organism record with same name: 'unknown'

FieldError: Cannot resolve keyword 'source' into field. Choices are: _previous_runs, artifacts, cell_lines, cell_markers, cell_types, created_at, created_by, created_by_id, currently_used, dataframe_artifact, dataframe_artifact_id, description, developmental_stages, diseases, entity, ethnicities, experimental_factors, genes, id, in_db, md5, name, organism, organisms, pathways, phenotypes, proteins, run, run_id, source_website, tissues, uid, updated_at, url, version

In [17]:
a = pd.read_parquet("../data/main/biomart_pos.parquet")

In [21]:
l = ['ENSG00000112096', 'ENSG00000137808', 'ENSG00000161149', 'ENSG00000182230', 'ENSG00000203812', 'ENSG00000204092', 'ENSG00000205485', 'ENSG00000212951', 'ENSG00000215271', 'ENSG00000221995', 'ENSG00000224739', 'ENSG00000224745', 'ENSG00000225178', 'ENSG00000225932', 'ENSG00000226377', 'ENSG00000226380', 'ENSG00000226403', 'ENSG00000227021', 'ENSG00000227220', 'ENSG00000227902', 'ENSG00000228139', 'ENSG00000228206', 'ENSG00000228906', 'ENSG00000229352', 'ENSG00000231575', 'ENSG00000232196', 'ENSG00000232295', 'ENSG00000233776', 'ENSG00000236166', 'ENSG00000236673', 'ENSG00000236740', 'ENSG00000236886', 'ENSG00000236996', 'ENSG00000237133', 'ENSG00000237513', 'ENSG00000237548', 'ENSG00000237838', 'ENSG00000239446', 'ENSG00000239467', 'ENSG00000239665', 'ENSG00000244693', 'ENSG00000244952', 'ENSG00000249860', 'ENSG00000251044', 'ENSG00000253878', 'ENSG00000254561', 'ENSG00000254740', 'ENSG00000255633', 'ENSG00000255823', 'ENSG00000256045', 'ENSG00000256222', 'ENSG00000256374', 'ENSG00000256427', 'ENSG00000256618', 'ENSG00000256863', 'ENSG00000256892', 'ENSG00000258414', 'ENSG00000258808', 'ENSG00000258861', 'ENSG00000259444', 'ENSG00000259820', 'ENSG00000259834', 'ENSG00000259855', 'ENSG00000260461', 'ENSG00000261068', 'ENSG00000261438', 'ENSG00000261490', 'ENSG00000261534', 'ENSG00000261737', 'ENSG00000261773', 'ENSG00000261963', 'ENSG00000262668', 'ENSG00000263464', 'ENSG00000267637', 'ENSG00000268955', 'ENSG00000269028', 'ENSG00000269900', 'ENSG00000269933', 'ENSG00000269966', 'ENSG00000270188', 'ENSG00000270394', 'ENSG00000270672', 'ENSG00000271043', 'ENSG00000271409', 'ENSG00000271734', 'ENSG00000271870', 'ENSG00000272040', 'ENSG00000272196', 'ENSG00000272267', 'ENSG00000272354', 'ENSG00000272370', 'ENSG00000272551', 'ENSG00000272567', 'ENSG00000272880', 'ENSG00000272904', 'ENSG00000272934', 'ENSG00000273301', 'ENSG00000273370', 'ENSG00000273496', 'ENSG00000273576', 'ENSG00000273614', 'ENSG00000273837', 'ENSG00000273888', 'ENSG00000273923', 'ENSG00000276612', 'ENSG00000276814', 'ENSG00000277050', 'ENSG00000277077', 'ENSG00000277352', 'ENSG00000277666', 'ENSG00000277761', 'ENSG00000278198', 'ENSG00000278782', 'ENSG00000278927', 'ENSG00000278955', 'ENSG00000279226', 'ENSG00000279765', 'ENSG00000279769', 'ENSG00000279948', 'ENSG00000280058', 'ENSG00000280095', 'ENSG00000280250', 'ENSG00000280346', 'ENSG00000280374', 'ENSG00000280710', 'ENSG00000282080', 'ENSG00000282246', 'ENSG00000282965', 'ENSG00000283486', 'ENSG00000284299', 'ENSG00000284741', 'ENSG00000285106', 'ENSG00000285162', 'ENSG00000285476', 'ENSG00000285762', 'ENSG00000286065', 'ENSG00000286228', 'ENSG00000286601', 'ENSG00000286699', 'ENSG00000286949', 'ENSG00000286996', 'ENSG00000287116', 'ENSG00000287388', 'ENSG00000288541', 'ENSG00000288546', 'ENSG00000288630', 'ENSG00000288639', 'ENSMUSG00000069518', 'ENSMUSG00000073682', 'ENSMUSG00000075014', 'ENSMUSG00000075015', 'ENSMUSG00000078091', 'ENSMUSG00000094958', 'ENSMUSG00000095547', 'ENSMUSG00000095891', 'ENSMUSG00000096385', 'ENSMUSG00000096519', 'ENSMUSG00000096923', 'ENSMUSG00000097078']

In [22]:
a = a.reindex(a.index.tolist() + l)

In [23]:
a.to_parquet("../data/main/biomart_pos.parquet")

In [22]:
pd.concat([table, table2]).to_parquet("../data/main/biomart_pos.parquet")